### PR TITLE
Feature/scrollable expected columns

### PR DESCRIPTION
**Pull request by Shriansh2002**
Resolved TF-168

https://github.com/tableflowhq/tableflow/assets/41548480/600a3bc0-732f-4d3a-aa3a-daa313975e69

### CODE REVIEW

**Review by ciminelli — CHANGES_REQUESTED** [review]
@Shriansh2002 looks great, one small issue I noticed. If you add a description to the column the tooltip is now cut off. Can you take a look?
Screenshot 2023-09-14 at 15 58 30

**Comment by ciminelli** [comment]
@Shriansh2002 since the issue only exists on this branch, are there CSS changes you can make here to fix it? If we need to you can update ui-library.

**Comment by Shriansh2002** [comment]
We need to make an adjustment to the tooltip's positioning, setting it to `left: 250%` or higher. This change is necessary because our table wrapper has `overflow: hidden` applied to enable scrolling functionality. As a result, the tooltip can't appear at the top of the screen as it normally would.

However, it's important to be aware that this adjustment may impact its appearance and functionality in other contexts where it is utilized.

**Comment by ciminelli** [comment]
@Shriansh2002 makes sense, @civan is going to make the updates to the tooltip component. The rest of the PR looks good we'll get it merged in soon!

**Review by ciminelli — APPROVED** [review]

**Pull request merged**
