### PR TITLE
Added code syntax highlighting using react-syntax-highlighter

### PR DESCRIPTION
**Pull request by Shriansh2002**
Resolves TF-173

**Dark Mode:**
Screenshot 2023-09-07 at 6 26 27 PM

**Light Mode:**
Screenshot 2023-09-07 at 6 27 10 PM

### CODE REVIEW

**Review by ciminelli — CHANGES_REQUESTED** [review]
Looking good! Is there any way we can use the light build version of react-syntax-highlighter? Since we only need js and jsx I think we can cut down on the code being imported: https://github.com/react-syntax-highlighter/react-syntax-highlighter#light-build

**Comment by Shriansh2002** [comment]
@ciminelli I have changed the build version to the Light Build version

**Review by ciminelli — COMMENTED** [review]
@Shriansh2002 looks great, however I'm getting this error in testing causing only the JS code to work with the syntax highlighter: 
Screenshot 2023-09-13 at 13 22 48

Is it happening for you as well?

**Comment by Shriansh2002** [comment]
There is an issue within the `react-syntax-highlighter` library's Light Build specifically related to rendering `jsx` code. You can find more details about this issue by visiting the following link:

[Issue Link](https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/337)

**Comment by ciminelli** [comment]
@Shriansh2002 is it not resolveable? Would just using js have enough highlighting? If you can take another look that would be great so we can release this.

**Comment by Shriansh2002** [comment]
@ciminelli If we are using only `js` for the language, then the look for the react code will be like this

Screenshot 2023-09-28 at 8 50 54 AM


As there are issues in the main repo of the `react-syntax-highlighter` either we need have to use the Normal Build for having the jsx color highlighting, or we can just use it like this

**Comment by ciminelli** [comment]
@Shriansh2002 let's just use `js` language for now. Thanks for the preview.

**Review by ciminelli — APPROVED** [review]

**Pull request merged**
